### ISSUE TITLE
主题分类

### ISSUE THREAD

**Issue by mingmings** [lenbo-ma/hexo-theme-vno#1]
hi 哥们你的主题挺好的，但是有个问题就是如何添加 category 呢，这个对于写博还是很必要的

**Comment by kevinma2010** [comment]
原作者的主题是没有分类功能的，所以我这个主题也不支持分类。

**Comment by lenbo-ma** [comment]
原作者的主题是没有分类功能的，所以我这个主题也不支持分类。

**Comment by lamaaa** [comment]
请问能不能让文章里的图片出现在主页呢

**Comment by mingmings** [comment]
写在 `<!--more-->` 之上不就出现了么

**Comment by lamaaa** [comment]
我尝试了几遍，不可以啊
![qq 20150729164913](https://cloud.githubusercontent.com/assets/11481498/8953532/ca584960-3611-11e5-8322-dabe66cb372c.png)
![qq 20150729165136](https://cloud.githubusercontent.com/assets/11481498/8953580/1f976ece-3612-11e5-80b2-366c4fa1e436.png)

能帮我看看在哪出错了吗？（我想要照片出现在主页那里）

**Comment by mingmings** [comment]
你看我这边的文章和效果其实是可以的，你文章是你本地的路径，推送到 github 上这个路径很明显是不生效的
![image](https://cloud.githubusercontent.com/assets/3365500/8953980/144ad8c8-3615-11e5-9192-8ef9d3b4bef4.png)

**Comment by lamaaa** [comment]
可是我改成用微博图床还是不行呢
![qq 20150729171823](https://cloud.githubusercontent.com/assets/11481498/8954094/daee30e2-3615-11e5-903c-31b2abd03cea.png)
你是用什么解决的？

**Comment by mingmings** [comment]
先确认从 github 上访问微博图床是否可行，另外把你的封面换乘非中文试试

**Comment by lamaaa** [comment]
我不知道怎么确认从github上访问微博图床是否可行，但是我查的资料有不少都是推荐用微博图床的。
我的照片在文章可以显示，只是不能在主页上显示，必须要阅读原文才能看到。
我试过在图片后，在前加一些文字。这些文字能在主页显示，但是图片却看不到了，只有阅读原文才看到。
哦对了，封面换成英文也不行。

**Comment by mingmings** [comment]
不知道是不是你主题禁止文章简介显示图片呢，其他方式我就不知道了

**Comment by kevinma2010** [comment]
目前文章列表还不支持格式化内容，晚点我会更新下这部分功能。你也可以push一个pr

**Comment by lamaaa** [comment]
如果不介意的话，能不能给我发下你的主题配置文件，我参考一下。
554026560@qq.com 谢谢。

**Comment by kevinma2010** [comment]
@lamaaa 我的主题配置文件就是master分支中的_config.yml

**Comment by lamaaa** [comment]
谢谢
