### ISSUE TITLE
Chrome下为什么布局有问题啊

### ISSUE THREAD

**Issue by ZhipingYang** [lenbo-ma/hexo-theme-vno#6]
Safari下就perfect。。

![qq20150625-1](https://cloud.githubusercontent.com/assets/9360037/8353305/fb8dae0c-1b6e-11e5-820b-7a4cfd8de1cd.png)
![qq20150625-2](https://cloud.githubusercontent.com/assets/9360037/8353315/132f9976-1b6f-11e5-827a-68a55151384e.png)

**Comment by kevinma2010** [comment]
我打开链接后看到的是正常的呀，有可能会是因为你放在github上，某些资源被墙了

**Comment by ZhipingYang** [comment]
不是被墙的原因，Safari浏览是没有问题的，网站是51offer.github.io

**Comment by kevinma2010** [comment]
你打开chrome调试工具，看下是不是有资源没有加载。我这边看是ok的

2015-06-26 7:47 GMT+08:00 Zhiping Yang notifications@github.com:

**Comment by ZhipingYang** [comment]
真的？请问是window还是Mac环境下的chrome

**Comment by kevinma2010** [comment]
Mac

2015-06-26 17:44 GMT+08:00 Zhiping Yang notifications@github.com:

**Comment by ZhipingYang** [comment]
不要逗我，你的chrome装了什么插件还是怎么，反正我们这边七个人的chrome都不行

**Comment by kevinma2010** [comment]
我用的http访问，不是https, cdn资源加载有问题

[image: 内嵌图片 1]

2015-06-27 9:55 GMT+08:00 Zhiping Yang notifications@github.com:

**Comment by kevinma2010** [comment]
之后会增加会https的检测
