### ISSUE TITLE
关于代码高亮的问题

### ISSUE THREAD

**Issue by qinyuanpei** [lenbo-ma/hexo-theme-vno#7]
这个主题的代码高亮我看了下，不太喜欢，想对此进行修改，和大部分Hexo主题一样它使用的代码高亮方案是[https://github.com/chriskempson/tomorrow-theme](https://github.com/chriskempson/tomorrow-theme)，可是不知道为什么改起来感觉好困难啊，请作者指点一二。谢谢！

**Comment by kevinma2010** [comment]
> Vno 使用经典的 tomorrow 主题作为默认的代码高亮配色。您也可以选择和使用您最喜欢的配色，将配色文件直接放到 assets/css 文件夹下， 然后将 default.hbs 中的 css/tomorrow.css 改为您的文件来使配置生效。想要更多的配色方案的话，可以看看[这个站点](http://jmblog.github.io/color-themes-for-highlightjs/)。

**Comment by lenbo-ma** [comment]
> Vno 使用经典的 tomorrow 主题作为默认的代码高亮配色。您也可以选择和使用您最喜欢的配色，将配色文件直接放到 assets/css 文件夹下， 然后将 default.hbs 中的 css/tomorrow.css 改为您的文件来使配置生效。想要更多的配色方案的话，可以看看[这个站点](http://jmblog.github.io/color-themes-for-highlightjs/)。
