### ISSUE TITLE
增加简书社交

### ISSUE THREAD

**Issue by bestswifter** [lenbo-ma/hexo-theme-vno#8]
太感谢这个项目了，博客比原来漂亮了很多，不过我不是做前端的，可否在社交部分添加一个简书的链接呢？

social:
  jianshu: "url"

**Comment by bestswifter** [comment]
在首页点击“项目作品”之后跳转的页面怎么实现呢？百度统计的JS代码加在哪里，如果能把详细的配置写在README.md里就更加感谢了

**Comment by monniya** [comment]
项目作品是需要自己单独写个页面，百度统计的代码可以加在[/layout/_partial/head.ejs](https://github.com/monniya/hexo-theme-new-vno/blob/master/layout/_partial/head.ejs)文件中，可以参考下我的（在主题基础上小小优化）

**Comment by kevinma2010** [comment]
停止维护。
